reserved = {
    "absolute": "ABSOLUTE",
    "and": "AND",
    "array": "ARRAY",
    "asm": "ASM",
    "begin": "BEGIN",
    "case": "CASE",
    "const": "CONST",
    "constructor": "CONSTRUCTOR",
    "destructor": "DESTRUCTOR",
    "external": "EXTERNAL",
    "div": "DIV",
    "do": "DO",
    "downto": "DOWNTO",
    "else": "ELSE",
    "end": "END",
    "file": "FILE",
    "for": "FOR",
    "forward": "FORWARD",
    "function": "FUNCTION",
    "goto": "GOTO",
    "if": "IF",
    "implementation": "IMPLEMENTATION",
    "in": "IN",
    "inline": "INLINE",
    "interface": "INTERFACE",
    "interrupt": "INTERRUPT",
    "label": "LABEL",
    "mod": "MOD",
    "nil": "NIL",
    "not": "NOT",
    "object": "OBJECT",
    "of": "OF",
    "or": "OR",
    "packed": "PACKED",
    "private": "PRIVATE",
    "procedure": "PROCEDURE",
    "program": "PROGRAM",
    "record": "RECORD",
    "repeat": "REPEAT",
    "set": "SET",
    "shl": "SHL",
    "shr": "SHR",
    "string": "STRING",
    "then": "THEN",
    "to": "TO",
    "type": "TYPE",
    "unit": "UNIT",
    "until": "UNTIL",
    "uses": "USES",
    "var": "VAR",
    "virtual": "VIRTUAL",
    "with": "WITH",
    "xor": "XOR",
    "integer": "INTEGER",
    "real": "REAL",
    "boolean": "BOOLEAN",
    "char": "CHAR",
    "true": "TRUE",
    "false": "FALSE",
    "while": "WHILE",
}

# Lista de tokens (se incluyen los reservados)
tokens = [
    "ID",
    "NUMBER",
    "ASIGNATION",
    "PLUS",
    "MINUS",
    "TIMES",
    "DIVIDE",
    "LESS",
    "LESSEQUAL",
    "GREATER",
    "GREATEREQUAL",
    "EQUAL",
    "DISTINT",
    "SEMICOLON",
    "COMMA",
    "LPAREN",
    "RPAREN",
    "LBRACKET",
    "RBRACKET",
    "COLON",
    "DOT",
    "DOBLEDOT",
    "CARET",
    "COMMENT",
] + list(reserved.values())
